version: "2"
formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/team-everfrost/remak-go
    golines:
      max-len: 120
      tab-len: 4
      shorten-comments: false
      reformat-tags: true
      chain-split-dots: true
  exclusions:
    generated: strict
    paths:
      - internal/dbgen
      - db/migrations/embed.go
linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - gocritic
    - lll
    - misspell
    - nilerr
    - noctx
    - prealloc
    - revive
  settings:
    lll:
      line-length: 120
      tab-width: 4
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: strict
    paths:
      - internal/dbgen
      - db/migrations/embed.go
run:
  timeout: 5m
  tests: true
