// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, email, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, image_url, role, plan, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.ImageUrl,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, account_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	AccountID uuid.UUID          `json:"account_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at < now() - interval '7 days'
   OR revoked_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (
  SELECT 1 FROM accounts WHERE email = $1 AND deleted_at IS NULL
)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, password_hash, name, image_url, role, plan, created_at, updated_at, deleted_at FROM accounts
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.ImageUrl,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, password_hash, name, image_url, role, plan, created_at, updated_at, deleted_at FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.ImageUrl,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, account_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageUsage = `-- name: GetStorageUsage :one
SELECT COALESCE(SUM(file_size), 0)::bigint AS usage
FROM documents
WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStorageUsage(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getStorageUsage, ownerID)
	var usage int64
	err := row.Scan(&usage)
	return usage, err
}

const lockAccountForStorage = `-- name: LockAccountForStorage :one
SELECT id, email, password_hash, name, image_url, role, plan, created_at, updated_at, deleted_at FROM accounts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockAccountForStorage(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, lockAccountForStorage, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.ImageUrl,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockActiveAccount = `-- name: LockActiveAccount :one
SELECT id, email, password_hash, name, image_url, role, plan, created_at, updated_at, deleted_at FROM accounts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockActiveAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, lockActiveAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.ImageUrl,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, accountID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const scheduleAccountArtifactCleanup = `-- name: ScheduleAccountArtifactCleanup :exec
INSERT INTO artifact_cleanup_jobs (id, document_id)
SELECT uuidv7(), document.id
FROM documents document
WHERE document.owner_id = $1
ON CONFLICT (document_id) DO UPDATE
SET state = 'QUEUED',
    attempt_count = 0,
    available_at = now(),
    last_error = NULL,
    completed_at = NULL,
    updated_at = now()
`

func (q *Queries) ScheduleAccountArtifactCleanup(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, scheduleAccountArtifactCleanup, ownerID)
	return err
}

const softDeleteAccount = `-- name: SoftDeleteAccount :execrows
UPDATE accounts
SET email = id::text || '@deleted.remak.invalid',
    password_hash = NULL,
    name = NULL,
    image_url = NULL,
    deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAccount(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteAccountDocuments = `-- name: SoftDeleteAccountDocuments :exec
UPDATE documents
SET deleted_at = COALESCE(deleted_at, now()), updated_at = now()
WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAccountDocuments(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAccountDocuments, ownerID)
	return err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE accounts
SET name = $2,
    image_url = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, image_url, role, plan, created_at, updated_at, deleted_at
`

type UpdateAccountProfileParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     pgtype.Text `json:"name"`
	ImageUrl pgtype.Text `json:"image_url"`
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile, arg.ID, arg.Name, arg.ImageUrl)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.ImageUrl,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE accounts
SET password_hash = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
