// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeChallenge = `-- name: ConsumeChallenge :execrows
UPDATE verification_challenges
SET consumed_at = now()
WHERE id = $1
  AND verified_at IS NOT NULL
  AND consumed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) ConsumeChallenge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentChallenges = `-- name: CountRecentChallenges :one
SELECT COUNT(*)::bigint
FROM verification_challenges
WHERE email = $1
  AND purpose = $2
  AND created_at > now() - interval '1 hour'
`

type CountRecentChallengesParams struct {
	Email   string           `json:"email"`
	Purpose ChallengePurpose `json:"purpose"`
}

func (q *Queries) CountRecentChallenges(ctx context.Context, arg CountRecentChallengesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentChallenges, arg.Email, arg.Purpose)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createVerificationChallenge = `-- name: CreateVerificationChallenge :one
INSERT INTO verification_challenges (
  id, email, purpose, code_hash, max_attempts, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, purpose, code_hash, attempt_count, max_attempts, expires_at, verified_at, consumed_at, created_at
`

type CreateVerificationChallengeParams struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Purpose     ChallengePurpose   `json:"purpose"`
	CodeHash    string             `json:"code_hash"`
	MaxAttempts int32              `json:"max_attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerificationChallenge(ctx context.Context, arg CreateVerificationChallengeParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, createVerificationChallenge,
		arg.ID,
		arg.Email,
		arg.Purpose,
		arg.CodeHash,
		arg.MaxAttempts,
		arg.ExpiresAt,
	)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChallengesByEmail = `-- name: DeleteChallengesByEmail :exec
DELETE FROM verification_challenges WHERE email = $1
`

func (q *Queries) DeleteChallengesByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteChallengesByEmail, email)
	return err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :exec
DELETE FROM verification_challenges
WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredChallenges)
	return err
}

const getLatestOpenChallenge = `-- name: GetLatestOpenChallenge :one
SELECT id, email, purpose, code_hash, attempt_count, max_attempts, expires_at, verified_at, consumed_at, created_at FROM verification_challenges
WHERE email = $1
  AND purpose = $2
  AND consumed_at IS NULL
  AND verified_at IS NULL
  AND expires_at > now()
  AND attempt_count < max_attempts
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOpenChallengeParams struct {
	Email   string           `json:"email"`
	Purpose ChallengePurpose `json:"purpose"`
}

func (q *Queries) GetLatestOpenChallenge(ctx context.Context, arg GetLatestOpenChallengeParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, getLatestOpenChallenge, arg.Email, arg.Purpose)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVerifiedChallenge = `-- name: GetLatestVerifiedChallenge :one
SELECT id, email, purpose, code_hash, attempt_count, max_attempts, expires_at, verified_at, consumed_at, created_at FROM verification_challenges
WHERE email = $1
  AND purpose = $2
  AND consumed_at IS NULL
  AND verified_at IS NOT NULL
  AND expires_at > now()
ORDER BY verified_at DESC
LIMIT 1
`

type GetLatestVerifiedChallengeParams struct {
	Email   string           `json:"email"`
	Purpose ChallengePurpose `json:"purpose"`
}

func (q *Queries) GetLatestVerifiedChallenge(ctx context.Context, arg GetLatestVerifiedChallengeParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, getLatestVerifiedChallenge, arg.Email, arg.Purpose)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationChallenge = `-- name: GetVerificationChallenge :one
SELECT id, email, purpose, code_hash, attempt_count, max_attempts, expires_at, verified_at, consumed_at, created_at FROM verification_challenges
WHERE id = $1
  AND email = $2
  AND purpose = $3
  AND consumed_at IS NULL
`

type GetVerificationChallengeParams struct {
	ID      uuid.UUID        `json:"id"`
	Email   string           `json:"email"`
	Purpose ChallengePurpose `json:"purpose"`
}

func (q *Queries) GetVerificationChallenge(ctx context.Context, arg GetVerificationChallengeParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, getVerificationChallenge, arg.ID, arg.Email, arg.Purpose)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementChallengeAttempt = `-- name: IncrementChallengeAttempt :one
UPDATE verification_challenges
SET attempt_count = attempt_count + 1
WHERE id = $1
  AND consumed_at IS NULL
  AND verified_at IS NULL
  AND expires_at > now()
  AND attempt_count < max_attempts
RETURNING id, email, purpose, code_hash, attempt_count, max_attempts, expires_at, verified_at, consumed_at, created_at
`

func (q *Queries) IncrementChallengeAttempt(ctx context.Context, id uuid.UUID) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, incrementChallengeAttempt, id)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markChallengeVerified = `-- name: MarkChallengeVerified :execrows
UPDATE verification_challenges
SET verified_at = now()
WHERE id = $1
  AND verified_at IS NULL
  AND consumed_at IS NULL
  AND expires_at > now()
  AND attempt_count <= max_attempts
`

func (q *Queries) MarkChallengeVerified(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markChallengeVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
