// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginWebpageRefresh = `-- name: BeginWebpageRefresh :one
UPDATE documents
SET title = $3,
    source_url = $4,
    current_version = current_version + 1,
    status = 'SCRAPE_PENDING',
    updated_at = now()
WHERE id = $1
  AND owner_id = $2
  AND type = 'WEBPAGE'
  AND deleted_at IS NULL
RETURNING id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector
`

type BeginWebpageRefreshParams struct {
	ID        uuid.UUID   `json:"id"`
	OwnerID   uuid.UUID   `json:"owner_id"`
	Title     pgtype.Text `json:"title"`
	SourceUrl pgtype.Text `json:"source_url"`
}

func (q *Queries) BeginWebpageRefresh(ctx context.Context, arg BeginWebpageRefreshParams) (Document, error) {
	row := q.db.QueryRow(ctx, beginWebpageRefresh,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.SourceUrl,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Type,
		&i.SourceUrl,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CurrentVersion,
		&i.ThumbnailUrl,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const claimArtifactCleanupJobs = `-- name: ClaimArtifactCleanupJobs :many
UPDATE artifact_cleanup_jobs
SET state = 'PROCESSING',
    attempt_count = attempt_count + 1,
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id IN (
  SELECT id
  FROM artifact_cleanup_jobs
  WHERE (
      state IN ('QUEUED', 'FAILED')
      OR (state = 'PROCESSING' AND updated_at < now() - interval '10 minutes')
    )
    AND available_at <= now()
    AND attempt_count < 10
  ORDER BY created_at
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, document_id, state, attempt_count, available_at, last_error, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ClaimArtifactCleanupJobs(ctx context.Context, batchSize int32) ([]ArtifactCleanupJob, error) {
	rows, err := q.db.Query(ctx, claimArtifactCleanupJobs, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactCleanupJob{}
	for rows.Next() {
		var i ArtifactCleanupJob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.State,
			&i.AttemptCount,
			&i.AvailableAt,
			&i.LastError,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeArtifactCleanupJob = `-- name: CompleteArtifactCleanupJob :execrows
UPDATE artifact_cleanup_jobs
SET state = 'SUCCEEDED', completed_at = now(), last_error = NULL, updated_at = now()
WHERE id = $1 AND state IN ('PROCESSING', 'SUCCEEDED')
`

func (q *Queries) CompleteArtifactCleanupJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completeArtifactCleanupJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeDocumentVersion = `-- name: CompleteDocumentVersion :execrows
UPDATE document_versions
SET raw_artifact_key = $3,
    content_artifact_key = $4,
    content_hash = $5,
    title = $6,
    content = $7,
    summary = $8,
    extraction_method = $9,
    completed_at = now()
WHERE document_id = $1 AND version = $2
`

type CompleteDocumentVersionParams struct {
	DocumentID         uuid.UUID   `json:"document_id"`
	Version            int32       `json:"version"`
	RawArtifactKey     pgtype.Text `json:"raw_artifact_key"`
	ContentArtifactKey pgtype.Text `json:"content_artifact_key"`
	ContentHash        pgtype.Text `json:"content_hash"`
	Title              pgtype.Text `json:"title"`
	Content            pgtype.Text `json:"content"`
	Summary            pgtype.Text `json:"summary"`
	ExtractionMethod   pgtype.Text `json:"extraction_method"`
}

func (q *Queries) CompleteDocumentVersion(ctx context.Context, arg CompleteDocumentVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.RawArtifactKey,
		arg.ContentArtifactKey,
		arg.ContentHash,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.ExtractionMethod,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeEnrichedVersion = `-- name: CompleteEnrichedVersion :execrows
UPDATE document_versions
SET summary = $3,
    completed_at = COALESCE(completed_at, now())
WHERE document_id = $1 AND version = $2
`

type CompleteEnrichedVersionParams struct {
	DocumentID uuid.UUID   `json:"document_id"`
	Version    int32       `json:"version"`
	Summary    pgtype.Text `json:"summary"`
}

func (q *Queries) CompleteEnrichedVersion(ctx context.Context, arg CompleteEnrichedVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeEnrichedVersion, arg.DocumentID, arg.Version, arg.Summary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeEnrichment = `-- name: CompleteEnrichment :execrows
UPDATE documents
SET summary = $3,
    status = 'COMPLETED',
    updated_at = now()
WHERE id = $1
  AND current_version = $2
  AND deleted_at IS NULL
`

type CompleteEnrichmentParams struct {
	ID             uuid.UUID   `json:"id"`
	CurrentVersion int32       `json:"current_version"`
	Summary        pgtype.Text `json:"summary"`
}

func (q *Queries) CompleteEnrichment(ctx context.Context, arg CompleteEnrichmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeEnrichment, arg.ID, arg.CurrentVersion, arg.Summary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeScrape = `-- name: CompleteScrape :execrows
UPDATE documents
SET title = COALESCE($3, title),
    content = $4,
    thumbnail_url = $5,
    file_size = $6,
    status = 'ENRICH_PENDING',
    updated_at = now()
WHERE id = $1
  AND current_version = $2
  AND deleted_at IS NULL
`

type CompleteScrapeParams struct {
	ID             uuid.UUID   `json:"id"`
	CurrentVersion int32       `json:"current_version"`
	Title          pgtype.Text `json:"title"`
	Content        pgtype.Text `json:"content"`
	ThumbnailUrl   pgtype.Text `json:"thumbnail_url"`
	FileSize       int64       `json:"file_size"`
}

func (q *Queries) CompleteScrape(ctx context.Context, arg CompleteScrapeParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeScrape,
		arg.ID,
		arg.CurrentVersion,
		arg.Title,
		arg.Content,
		arg.ThumbnailUrl,
		arg.FileSize,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOwnedDocumentsByIDs = `-- name: CountOwnedDocumentsByIDs :one
SELECT COUNT(*)::bigint
FROM documents
WHERE owner_id = $1
  AND id = ANY($2::uuid[])
  AND deleted_at IS NULL
`

type CountOwnedDocumentsByIDsParams struct {
	OwnerID     uuid.UUID   `json:"owner_id"`
	DocumentIds []uuid.UUID `json:"document_ids"`
}

func (q *Queries) CountOwnedDocumentsByIDs(ctx context.Context, arg CountOwnedDocumentsByIDsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedDocumentsByIDs, arg.OwnerID, arg.DocumentIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createArtifactCleanupJob = `-- name: CreateArtifactCleanupJob :exec
INSERT INTO artifact_cleanup_jobs (id, document_id)
VALUES ($1, $2)
ON CONFLICT (document_id) DO NOTHING
`

type CreateArtifactCleanupJobParams struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
}

func (q *Queries) CreateArtifactCleanupJob(ctx context.Context, arg CreateArtifactCleanupJobParams) error {
	_, err := q.db.Exec(ctx, createArtifactCleanupJob, arg.ID, arg.DocumentID)
	return err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (id, document_id, version, title, content, media_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, document_id, version, raw_artifact_key, content_artifact_key, content_hash, title, content, summary, extraction_method, created_at, completed_at, media_type
`

type CreateDocumentVersionParams struct {
	ID         uuid.UUID   `json:"id"`
	DocumentID uuid.UUID   `json:"document_id"`
	Version    int32       `json:"version"`
	Title      pgtype.Text `json:"title"`
	Content    pgtype.Text `json:"content"`
	MediaType  pgtype.Text `json:"media_type"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.Version,
		arg.Title,
		arg.Content,
		arg.MediaType,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.RawArtifactKey,
		&i.ContentArtifactKey,
		&i.ContentHash,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.ExtractionMethod,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.MediaType,
	)
	return i, err
}

const createFileDocument = `-- name: CreateFileDocument :one
INSERT INTO documents (
  id, owner_id, title, type, content, status, current_version, file_size
)
VALUES ($1, $2, $3, $4, $5, $6, 1, $7)
RETURNING id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector
`

type CreateFileDocumentParams struct {
	ID       uuid.UUID      `json:"id"`
	OwnerID  uuid.UUID      `json:"owner_id"`
	Title    pgtype.Text    `json:"title"`
	Type     DocumentType   `json:"type"`
	Content  pgtype.Text    `json:"content"`
	Status   DocumentStatus `json:"status"`
	FileSize int64          `json:"file_size"`
}

func (q *Queries) CreateFileDocument(ctx context.Context, arg CreateFileDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createFileDocument,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Type,
		arg.Content,
		arg.Status,
		arg.FileSize,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Type,
		&i.SourceUrl,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CurrentVersion,
		&i.ThumbnailUrl,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const createMemo = `-- name: CreateMemo :one
INSERT INTO documents (
  id, owner_id, title, type, content, status, current_version
)
VALUES ($1, $2, $3, 'MEMO', $4, 'ENRICH_PENDING', 1)
RETURNING id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector
`

type CreateMemoParams struct {
	ID      uuid.UUID   `json:"id"`
	OwnerID uuid.UUID   `json:"owner_id"`
	Title   pgtype.Text `json:"title"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) CreateMemo(ctx context.Context, arg CreateMemoParams) (Document, error) {
	row := q.db.QueryRow(ctx, createMemo,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Content,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Type,
		&i.SourceUrl,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CurrentVersion,
		&i.ThumbnailUrl,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const createWebpage = `-- name: CreateWebpage :one
INSERT INTO documents (
  id, owner_id, title, type, source_url, status, current_version
)
VALUES ($1, $2, $3, 'WEBPAGE', $4, 'SCRAPE_PENDING', 1)
RETURNING id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector
`

type CreateWebpageParams struct {
	ID        uuid.UUID   `json:"id"`
	OwnerID   uuid.UUID   `json:"owner_id"`
	Title     pgtype.Text `json:"title"`
	SourceUrl pgtype.Text `json:"source_url"`
}

func (q *Queries) CreateWebpage(ctx context.Context, arg CreateWebpageParams) (Document, error) {
	row := q.db.QueryRow(ctx, createWebpage,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.SourceUrl,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Type,
		&i.SourceUrl,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CurrentVersion,
		&i.ThumbnailUrl,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const failArtifactCleanupJob = `-- name: FailArtifactCleanupJob :execrows
UPDATE artifact_cleanup_jobs
SET state = 'FAILED',
    last_error = $2,
    available_at = now() + ($3::bigint * interval '1 second'),
    completed_at = now(),
    updated_at = now()
WHERE id = $1 AND state = 'PROCESSING'
`

type FailArtifactCleanupJobParams struct {
	ID             uuid.UUID   `json:"id"`
	LastError      pgtype.Text `json:"last_error"`
	BackoffSeconds int64       `json:"backoff_seconds"`
}

func (q *Queries) FailArtifactCleanupJob(ctx context.Context, arg FailArtifactCleanupJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failArtifactCleanupJob, arg.ID, arg.LastError, arg.BackoffSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector FROM documents
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Type,
		&i.SourceUrl,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CurrentVersion,
		&i.ThumbnailUrl,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, version, raw_artifact_key, content_artifact_key, content_hash, title, content, summary, extraction_method, created_at, completed_at, media_type FROM document_versions
WHERE document_id = $1 AND version = $2
`

type GetDocumentVersionParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Version    int32     `json:"version"`
}

func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.Version)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.RawArtifactKey,
		&i.ContentArtifactKey,
		&i.ContentHash,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.ExtractionMethod,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.MediaType,
	)
	return i, err
}

const getOwnedCurrentDocumentVersion = `-- name: GetOwnedCurrentDocumentVersion :one
SELECT dv.id, dv.document_id, dv.version, dv.raw_artifact_key, dv.content_artifact_key, dv.content_hash, dv.title, dv.content, dv.summary, dv.extraction_method, dv.created_at, dv.completed_at, dv.media_type
FROM document_versions dv
JOIN documents d ON d.id = dv.document_id AND d.current_version = dv.version
WHERE d.id = $1
  AND d.owner_id = $2
  AND d.deleted_at IS NULL
`

type GetOwnedCurrentDocumentVersionParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetOwnedCurrentDocumentVersion(ctx context.Context, arg GetOwnedCurrentDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getOwnedCurrentDocumentVersion, arg.ID, arg.OwnerID)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.RawArtifactKey,
		&i.ContentArtifactKey,
		&i.ContentHash,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.ExtractionMethod,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.MediaType,
	)
	return i, err
}

const getOwnedDocument = `-- name: GetOwnedDocument :one
SELECT id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector FROM documents
WHERE id = $1
  AND owner_id = $2
  AND deleted_at IS NULL
`

type GetOwnedDocumentParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetOwnedDocument(ctx context.Context, arg GetOwnedDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getOwnedDocument, arg.ID, arg.OwnerID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Type,
		&i.SourceUrl,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CurrentVersion,
		&i.ThumbnailUrl,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const getOwnedDocumentsByIDs = `-- name: GetOwnedDocumentsByIDs :many
SELECT id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector FROM documents
WHERE owner_id = $1
  AND id = ANY($2::uuid[])
  AND deleted_at IS NULL
`

type GetOwnedDocumentsByIDsParams struct {
	OwnerID     uuid.UUID   `json:"owner_id"`
	DocumentIds []uuid.UUID `json:"document_ids"`
}

func (q *Queries) GetOwnedDocumentsByIDs(ctx context.Context, arg GetOwnedDocumentsByIDsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, getOwnedDocumentsByIDs, arg.OwnerID, arg.DocumentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Type,
			&i.SourceUrl,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CurrentVersion,
			&i.ThumbnailUrl,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentArtifactKeys = `-- name: ListDocumentArtifactKeys :many
SELECT d.type, version.raw_artifact_key AS key
FROM documents d
JOIN document_versions version ON version.document_id = d.id
WHERE d.id = $1
  AND version.raw_artifact_key IS NOT NULL
UNION ALL
SELECT d.type, version.content_artifact_key AS key
FROM documents d
JOIN document_versions version ON version.document_id = d.id
WHERE d.id = $1
  AND version.content_artifact_key IS NOT NULL
`

type ListDocumentArtifactKeysRow struct {
	Type DocumentType `json:"type"`
	Key  pgtype.Text  `json:"key"`
}

func (q *Queries) ListDocumentArtifactKeys(ctx context.Context, documentID uuid.UUID) ([]ListDocumentArtifactKeysRow, error) {
	rows, err := q.db.Query(ctx, listDocumentArtifactKeys, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentArtifactKeysRow{}
	for rows.Next() {
		var i ListDocumentArtifactKeysRow
		if err := rows.Scan(&i.Type, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTagNames = `-- name: ListDocumentTagNames :many
SELECT dt.document_id, t.name
FROM document_tags dt
JOIN tags t ON t.id = dt.tag_id
JOIN documents d ON d.id = dt.document_id
WHERE d.owner_id = $1::uuid
  AND dt.document_id = ANY($2::uuid[])
  AND d.deleted_at IS NULL
ORDER BY t.name
`

type ListDocumentTagNamesParams struct {
	OwnerID     uuid.UUID   `json:"owner_id"`
	DocumentIds []uuid.UUID `json:"document_ids"`
}

type ListDocumentTagNamesRow struct {
	DocumentID uuid.UUID `json:"document_id"`
	Name       string    `json:"name"`
}

func (q *Queries) ListDocumentTagNames(ctx context.Context, arg ListDocumentTagNamesParams) ([]ListDocumentTagNamesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentTagNames, arg.OwnerID, arg.DocumentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentTagNamesRow{}
	for rows.Next() {
		var i ListDocumentTagNamesRow
		if err := rows.Scan(&i.DocumentID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT d.id, d.owner_id, d.title, d.type, d.source_url, d.content, d.summary, d.status, d.current_version, d.thumbnail_url, d.file_size, d.created_at, d.updated_at, d.deleted_at, d.search_vector FROM documents d
WHERE d.owner_id = $1
  AND d.deleted_at IS NULL
  AND (
    $3::uuid IS NULL
    OR (d.created_at, d.id) < (
      SELECT cursor_document.created_at, cursor_document.id
      FROM documents cursor_document
      WHERE cursor_document.id = $3::uuid
        AND cursor_document.owner_id = $1
    )
  )
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2
`

type ListDocumentsParams struct {
	OwnerID  uuid.UUID   `json:"owner_id"`
	Limit    int32       `json:"limit"`
	CursorID pgtype.UUID `json:"cursor_id"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.OwnerID, arg.Limit, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Type,
			&i.SourceUrl,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CurrentVersion,
			&i.ThumbnailUrl,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByCollection = `-- name: ListDocumentsByCollection :many
SELECT d.id, d.owner_id, d.title, d.type, d.source_url, d.content, d.summary, d.status, d.current_version, d.thumbnail_url, d.file_size, d.created_at, d.updated_at, d.deleted_at, d.search_vector
FROM documents d
JOIN collection_documents cd ON cd.document_id = d.id
JOIN collections c ON c.id = cd.collection_id
WHERE d.owner_id = $1
  AND c.owner_id = $1
  AND c.name = $2
  AND d.deleted_at IS NULL
  AND (
    $4::uuid IS NULL
    OR (d.created_at, d.id) < (
      SELECT cursor_document.created_at, cursor_document.id
      FROM documents cursor_document
      WHERE cursor_document.id = $4::uuid
        AND cursor_document.owner_id = $1
    )
  )
ORDER BY d.created_at DESC, d.id DESC
LIMIT $3
`

type ListDocumentsByCollectionParams struct {
	OwnerID  uuid.UUID   `json:"owner_id"`
	Name     string      `json:"name"`
	Limit    int32       `json:"limit"`
	CursorID pgtype.UUID `json:"cursor_id"`
}

func (q *Queries) ListDocumentsByCollection(ctx context.Context, arg ListDocumentsByCollectionParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByCollection,
		arg.OwnerID,
		arg.Name,
		arg.Limit,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Type,
			&i.SourceUrl,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CurrentVersion,
			&i.ThumbnailUrl,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTag = `-- name: ListDocumentsByTag :many
SELECT d.id, d.owner_id, d.title, d.type, d.source_url, d.content, d.summary, d.status, d.current_version, d.thumbnail_url, d.file_size, d.created_at, d.updated_at, d.deleted_at, d.search_vector
FROM documents d
JOIN document_tags dt ON dt.document_id = d.id
JOIN tags t ON t.id = dt.tag_id
WHERE d.owner_id = $1
  AND t.owner_id = $1
  AND t.name = $2
  AND d.deleted_at IS NULL
  AND (
    $4::uuid IS NULL
    OR (d.created_at, d.id) < (
      SELECT cursor_document.created_at, cursor_document.id
      FROM documents cursor_document
      WHERE cursor_document.id = $4::uuid
        AND cursor_document.owner_id = $1
    )
  )
ORDER BY d.created_at DESC, d.id DESC
LIMIT $3
`

type ListDocumentsByTagParams struct {
	OwnerID  uuid.UUID   `json:"owner_id"`
	Name     string      `json:"name"`
	Limit    int32       `json:"limit"`
	CursorID pgtype.UUID `json:"cursor_id"`
}

func (q *Queries) ListDocumentsByTag(ctx context.Context, arg ListDocumentsByTagParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByTag,
		arg.OwnerID,
		arg.Name,
		arg.Limit,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Type,
			&i.SourceUrl,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CurrentVersion,
			&i.ThumbnailUrl,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentEnrichProcessing = `-- name: MarkDocumentEnrichProcessing :execrows
UPDATE documents
SET status = 'ENRICH_PROCESSING', updated_at = now()
WHERE id = $1
  AND current_version = $2
  AND status IN ('ENRICH_PENDING', 'ENRICH_REJECTED')
  AND deleted_at IS NULL
`

type MarkDocumentEnrichProcessingParams struct {
	ID             uuid.UUID `json:"id"`
	CurrentVersion int32     `json:"current_version"`
}

func (q *Queries) MarkDocumentEnrichProcessing(ctx context.Context, arg MarkDocumentEnrichProcessingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentEnrichProcessing, arg.ID, arg.CurrentVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentProcessing = `-- name: MarkDocumentProcessing :execrows
UPDATE documents
SET status = 'SCRAPE_PROCESSING', updated_at = now()
WHERE id = $1
  AND current_version = $2
  AND status IN ('SCRAPE_PENDING', 'SCRAPE_REJECTED')
`

type MarkDocumentProcessingParams struct {
	ID             uuid.UUID `json:"id"`
	CurrentVersion int32     `json:"current_version"`
}

func (q *Queries) MarkDocumentProcessing(ctx context.Context, arg MarkDocumentProcessingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentProcessing, arg.ID, arg.CurrentVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectEnrichment = `-- name: RejectEnrichment :execrows
UPDATE documents
SET status = 'ENRICH_REJECTED', updated_at = now()
WHERE id = $1
  AND current_version = $2
  AND deleted_at IS NULL
`

type RejectEnrichmentParams struct {
	ID             uuid.UUID `json:"id"`
	CurrentVersion int32     `json:"current_version"`
}

func (q *Queries) RejectEnrichment(ctx context.Context, arg RejectEnrichmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectEnrichment, arg.ID, arg.CurrentVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectScrape = `-- name: RejectScrape :execrows
UPDATE documents
SET status = 'SCRAPE_REJECTED', updated_at = now()
WHERE id = $1
  AND current_version = $2
  AND deleted_at IS NULL
`

type RejectScrapeParams struct {
	ID             uuid.UUID `json:"id"`
	CurrentVersion int32     `json:"current_version"`
}

func (q *Queries) RejectScrape(ctx context.Context, arg RejectScrapeParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectScrape, arg.ID, arg.CurrentVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueArtifactCleanupJob = `-- name: RequeueArtifactCleanupJob :execrows
UPDATE artifact_cleanup_jobs
SET state = 'QUEUED',
    attempt_count = 0,
    available_at = now(),
    last_error = NULL,
    completed_at = NULL,
    updated_at = now()
WHERE document_id = $1
`

func (q *Queries) RequeueArtifactCleanupJob(ctx context.Context, documentID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requeueArtifactCleanupJob, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveExtractedContent = `-- name: SaveExtractedContent :execrows
WITH updated_version AS (
  UPDATE document_versions
  SET content = $1,
      content_hash = $3,
      extraction_method = $4,
      completed_at = COALESCE(completed_at, now())
  WHERE document_id = $5
    AND version = $2
  RETURNING document_id
)
UPDATE documents
SET content = $1, updated_at = now()
WHERE id IN (SELECT document_id FROM updated_version)
  AND current_version = $2
  AND deleted_at IS NULL
`

type SaveExtractedContentParams struct {
	Content          pgtype.Text `json:"content"`
	Version          int32       `json:"version"`
	ContentHash      pgtype.Text `json:"content_hash"`
	ExtractionMethod pgtype.Text `json:"extraction_method"`
	DocumentID       uuid.UUID   `json:"document_id"`
}

func (q *Queries) SaveExtractedContent(ctx context.Context, arg SaveExtractedContentParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveExtractedContent,
		arg.Content,
		arg.Version,
		arg.ContentHash,
		arg.ExtractionMethod,
		arg.DocumentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchDocumentsText = `-- name: SearchDocumentsText :many
SELECT id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector FROM documents
WHERE owner_id = $1::uuid
  AND deleted_at IS NULL
  AND (
    title ILIKE '%' || $2 || '%'
    OR content ILIKE '%' || $2 || '%'
    OR summary ILIKE '%' || $2 || '%'
  )
ORDER BY
  CASE WHEN title ILIKE '%' || $2 || '%' THEN 0 ELSE 1 END,
  similarity(COALESCE(title, ''), $2) DESC,
  updated_at DESC
LIMIT $4::int OFFSET $3::int
`

type SearchDocumentsTextParams struct {
	OwnerID    uuid.UUID   `json:"owner_id"`
	Query      pgtype.Text `json:"query"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) SearchDocumentsText(ctx context.Context, arg SearchDocumentsTextParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, searchDocumentsText,
		arg.OwnerID,
		arg.Query,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Type,
			&i.SourceUrl,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CurrentVersion,
			&i.ThumbnailUrl,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :execrows
UPDATE documents
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type SoftDeleteDocumentParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDocument, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemo = `-- name: UpdateMemo :one
UPDATE documents
SET title = $3,
    content = $4,
    current_version = current_version + 1,
    status = 'ENRICH_PENDING',
    updated_at = now()
WHERE id = $1
  AND owner_id = $2
  AND type = 'MEMO'
  AND deleted_at IS NULL
RETURNING id, owner_id, title, type, source_url, content, summary, status, current_version, thumbnail_url, file_size, created_at, updated_at, deleted_at, search_vector
`

type UpdateMemoParams struct {
	ID      uuid.UUID   `json:"id"`
	OwnerID uuid.UUID   `json:"owner_id"`
	Title   pgtype.Text `json:"title"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) UpdateMemo(ctx context.Context, arg UpdateMemoParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateMemo,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Content,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Type,
		&i.SourceUrl,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CurrentVersion,
		&i.ThumbnailUrl,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}
