// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const claimEnrichmentJobs = `-- name: ClaimEnrichmentJobs :many
UPDATE ingestion_jobs
SET state = 'PROCESSING',
    attempt_count = attempt_count + 1,
    started_at = COALESCE(started_at, now()),
    completed_at = NULL,
    updated_at = now()
WHERE id IN (
  SELECT id
  FROM ingestion_jobs
  WHERE type = 'ENRICH'
    AND (
      state IN ('QUEUED', 'FAILED')
      OR (state = 'PROCESSING' AND updated_at < now() - interval '10 minutes')
    )
    AND available_at <= now()
    AND attempt_count < 5
  ORDER BY created_at
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, document_id, document_version, type, state, attempt_count, last_error_code, last_error_message, available_at, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ClaimEnrichmentJobs(ctx context.Context, limit int32) ([]IngestionJob, error) {
	rows, err := q.db.Query(ctx, claimEnrichmentJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionJob{}
	for rows.Next() {
		var i IngestionJob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.DocumentVersion,
			&i.Type,
			&i.State,
			&i.AttemptCount,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.AvailableAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
UPDATE outbox_events
SET lock_token = $1,
    locked_until = now() + interval '30 seconds'
WHERE id IN (
  SELECT id
  FROM outbox_events
  WHERE published_at IS NULL
    AND dead_lettered_at IS NULL
    AND available_at <= now()
    AND (locked_until IS NULL OR locked_until < now())
  ORDER BY created_at
  LIMIT $2
  FOR UPDATE SKIP LOCKED
)
RETURNING id, event_type, aggregate_id, payload, attempt_count, available_at, lock_token, locked_until, published_at, dead_lettered_at, last_error, created_at
`

type ClaimOutboxEventsParams struct {
	LockToken pgtype.UUID `json:"lock_token"`
	BatchSize int32       `json:"batch_size"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, arg.LockToken, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.Payload,
			&i.AttemptCount,
			&i.AvailableAt,
			&i.LockToken,
			&i.LockedUntil,
			&i.PublishedAt,
			&i.DeadLetteredAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeInboxEvent = `-- name: CompleteInboxEvent :exec
UPDATE inbox_events
SET processed_at = now(), last_error = NULL
WHERE event_id = $1
`

func (q *Queries) CompleteInboxEvent(ctx context.Context, eventID string) error {
	_, err := q.db.Exec(ctx, completeInboxEvent, eventID)
	return err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE ingestion_jobs
SET state = 'SUCCEEDED', completed_at = now(), updated_at = now()
WHERE id = $1 AND state IN ('QUEUED', 'PROCESSING', 'SUCCEEDED')
`

func (q *Queries) CompleteJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createChunk = `-- name: CreateChunk :exec
INSERT INTO chunks (
  id, document_id, document_version, chunk_index, section_title,
  content, page_number, embedding_model, embedding
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateChunkParams struct {
	ID              uuid.UUID       `json:"id"`
	DocumentID      uuid.UUID       `json:"document_id"`
	DocumentVersion int32           `json:"document_version"`
	ChunkIndex      int32           `json:"chunk_index"`
	SectionTitle    pgtype.Text     `json:"section_title"`
	Content         string          `json:"content"`
	PageNumber      pgtype.Int4     `json:"page_number"`
	EmbeddingModel  string          `json:"embedding_model"`
	Embedding       pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) error {
	_, err := q.db.Exec(ctx, createChunk,
		arg.ID,
		arg.DocumentID,
		arg.DocumentVersion,
		arg.ChunkIndex,
		arg.SectionTitle,
		arg.Content,
		arg.PageNumber,
		arg.EmbeddingModel,
		arg.Embedding,
	)
	return err
}

const createIngestionJob = `-- name: CreateIngestionJob :one
INSERT INTO ingestion_jobs (
  id, document_id, document_version, type, state
)
VALUES ($1, $2, $3, $4, 'QUEUED')
ON CONFLICT (document_id, document_version, type)
DO UPDATE SET updated_at = ingestion_jobs.updated_at
RETURNING id, document_id, document_version, type, state, attempt_count, last_error_code, last_error_message, available_at, started_at, completed_at, created_at, updated_at
`

type CreateIngestionJobParams struct {
	ID              uuid.UUID        `json:"id"`
	DocumentID      uuid.UUID        `json:"document_id"`
	DocumentVersion int32            `json:"document_version"`
	Type            IngestionJobType `json:"type"`
}

func (q *Queries) CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (IngestionJob, error) {
	row := q.db.QueryRow(ctx, createIngestionJob,
		arg.ID,
		arg.DocumentID,
		arg.DocumentVersion,
		arg.Type,
	)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.DocumentVersion,
		&i.Type,
		&i.State,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (id, event_type, aggregate_id, payload)
VALUES ($1, $2, $3, $4)
`

type CreateOutboxEventParams struct {
	ID          uuid.UUID `json:"id"`
	EventType   string    `json:"event_type"`
	AggregateID uuid.UUID `json:"aggregate_id"`
	Payload     []byte    `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.Payload,
	)
	return err
}

const deadLetterOutboxEvent = `-- name: DeadLetterOutboxEvent :execrows
UPDATE outbox_events
SET attempt_count = attempt_count + 1,
    last_error = $2,
    dead_lettered_at = now(),
    lock_token = NULL,
    locked_until = NULL
WHERE id = $1 AND lock_token = $3 AND published_at IS NULL
`

type DeadLetterOutboxEventParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
	LockToken pgtype.UUID `json:"lock_token"`
}

func (q *Queries) DeadLetterOutboxEvent(ctx context.Context, arg DeadLetterOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterOutboxEvent, arg.ID, arg.LastError, arg.LockToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failInboxEvent = `-- name: FailInboxEvent :exec
UPDATE inbox_events
SET last_error = $2
WHERE event_id = $1
`

type FailInboxEventParams struct {
	EventID   string      `json:"event_id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailInboxEvent(ctx context.Context, arg FailInboxEventParams) error {
	_, err := q.db.Exec(ctx, failInboxEvent, arg.EventID, arg.LastError)
	return err
}

const failJob = `-- name: FailJob :execrows
UPDATE ingestion_jobs
SET state = 'FAILED',
    last_error_code = $2,
    last_error_message = $3,
    available_at = now() + ($4::bigint * interval '1 second'),
    completed_at = now(),
    updated_at = now()
WHERE id = $1 AND state IN ('QUEUED', 'PROCESSING')
`

type FailJobParams struct {
	ID               uuid.UUID   `json:"id"`
	LastErrorCode    pgtype.Text `json:"last_error_code"`
	LastErrorMessage pgtype.Text `json:"last_error_message"`
	BackoffSeconds   int64       `json:"backoff_seconds"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJob,
		arg.ID,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.BackoffSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIngestionJob = `-- name: GetIngestionJob :one
SELECT id, document_id, document_version, type, state, attempt_count, last_error_code, last_error_message, available_at, started_at, completed_at, created_at, updated_at FROM ingestion_jobs WHERE id = $1
`

func (q *Queries) GetIngestionJob(ctx context.Context, id uuid.UUID) (IngestionJob, error) {
	row := q.db.QueryRow(ctx, getIngestionJob, id)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.DocumentVersion,
		&i.Type,
		&i.State,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJobProcessing = `-- name: MarkJobProcessing :execrows
UPDATE ingestion_jobs
SET state = 'PROCESSING',
    attempt_count = attempt_count + 1,
    started_at = COALESCE(started_at, now()),
    completed_at = NULL,
    updated_at = now()
WHERE id = $1 AND state IN ('QUEUED', 'FAILED')
`

func (q *Queries) MarkJobProcessing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markJobProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE outbox_events
SET published_at = now(), last_error = NULL
WHERE id = $1 AND lock_token = $2 AND published_at IS NULL
`

type MarkOutboxPublishedParams struct {
	ID        uuid.UUID   `json:"id"`
	LockToken pgtype.UUID `json:"lock_token"`
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublished, arg.ID, arg.LockToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerInboxEvent = `-- name: RegisterInboxEvent :one
INSERT INTO inbox_events (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

type RegisterInboxEventParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) RegisterInboxEvent(ctx context.Context, arg RegisterInboxEventParams) (string, error) {
	row := q.db.QueryRow(ctx, registerInboxEvent, arg.EventID, arg.EventType)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}

const replaceChunks = `-- name: ReplaceChunks :exec
DELETE FROM chunks
WHERE document_id = $1 AND document_version = $2
`

type ReplaceChunksParams struct {
	DocumentID      uuid.UUID `json:"document_id"`
	DocumentVersion int32     `json:"document_version"`
}

func (q *Queries) ReplaceChunks(ctx context.Context, arg ReplaceChunksParams) error {
	_, err := q.db.Exec(ctx, replaceChunks, arg.DocumentID, arg.DocumentVersion)
	return err
}

const rescheduleOutboxEvent = `-- name: RescheduleOutboxEvent :exec
UPDATE outbox_events
SET attempt_count = attempt_count + 1,
    available_at = now() + ($1::bigint * interval '1 second'),
    last_error = $2,
    lock_token = NULL,
    locked_until = NULL
WHERE id = $3 AND lock_token = $4 AND published_at IS NULL
`

type RescheduleOutboxEventParams struct {
	BackoffSeconds int64       `json:"backoff_seconds"`
	LastError      pgtype.Text `json:"last_error"`
	ID             uuid.UUID   `json:"id"`
	LockToken      pgtype.UUID `json:"lock_token"`
}

func (q *Queries) RescheduleOutboxEvent(ctx context.Context, arg RescheduleOutboxEventParams) error {
	_, err := q.db.Exec(ctx, rescheduleOutboxEvent,
		arg.BackoffSeconds,
		arg.LastError,
		arg.ID,
		arg.LockToken,
	)
	return err
}

const searchChunksVector = `-- name: SearchChunksVector :many
WITH vector_settings AS MATERIALIZED (
  SELECT set_config('hnsw.iterative_scan', 'relaxed_order', true)
),
relaxed_results AS MATERIALIZED (
  SELECT c.id, c.document_id, c.document_version, c.chunk_index, c.section_title, c.content, c.page_number, c.embedding_model, c.embedding, c.created_at, d.id AS document_public_id, d.title AS document_title,
         (c.embedding <=> $1::vector)::float8 AS distance
  FROM vector_settings
  CROSS JOIN chunks c
  JOIN documents d ON d.id = c.document_id
  WHERE d.owner_id = $2::uuid
    AND d.deleted_at IS NULL
    AND c.document_version = d.current_version
    AND c.embedding IS NOT NULL
  ORDER BY c.embedding <=> $1::vector
  LIMIT $3::int
)
SELECT id, document_id, document_version, chunk_index, section_title, content,
       page_number, embedding_model, embedding, created_at,
       document_public_id, document_title, (1 - distance)::float8 AS score
FROM relaxed_results
ORDER BY distance + 0
`

type SearchChunksVectorParams struct {
	Embedding      pgvector_go.Vector `json:"embedding"`
	OwnerID        uuid.UUID          `json:"owner_id"`
	CandidateLimit int32              `json:"candidate_limit"`
}

type SearchChunksVectorRow struct {
	ID               uuid.UUID          `json:"id"`
	DocumentID       uuid.UUID          `json:"document_id"`
	DocumentVersion  int32              `json:"document_version"`
	ChunkIndex       int32              `json:"chunk_index"`
	SectionTitle     pgtype.Text        `json:"section_title"`
	Content          string             `json:"content"`
	PageNumber       pgtype.Int4        `json:"page_number"`
	EmbeddingModel   string             `json:"embedding_model"`
	Embedding        pgvector.Vector    `json:"embedding"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DocumentPublicID uuid.UUID          `json:"document_public_id"`
	DocumentTitle    pgtype.Text        `json:"document_title"`
	Score            float64            `json:"score"`
}

// pgvector 0.8 relaxed scans can be slightly out of order. PostgreSQL 18 needs
// the explicit expression to perform a strict final ordering.
func (q *Queries) SearchChunksVector(ctx context.Context, arg SearchChunksVectorParams) ([]SearchChunksVectorRow, error) {
	rows, err := q.db.Query(ctx, searchChunksVector, arg.Embedding, arg.OwnerID, arg.CandidateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchChunksVectorRow{}
	for rows.Next() {
		var i SearchChunksVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.DocumentVersion,
			&i.ChunkIndex,
			&i.SectionTitle,
			&i.Content,
			&i.PageNumber,
			&i.EmbeddingModel,
			&i.Embedding,
			&i.CreatedAt,
			&i.DocumentPublicID,
			&i.DocumentTitle,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
