// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package dbgen

import (
	"context"
)

const deleteOldInboxEvents = `-- name: DeleteOldInboxEvents :execrows
DELETE FROM inbox_events
WHERE processed_at < now() - interval '30 days'
`

func (q *Queries) DeleteOldInboxEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldInboxEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldIngestionJobs = `-- name: DeleteOldIngestionJobs :execrows
DELETE FROM ingestion_jobs
WHERE state IN ('SUCCEEDED', 'CANCELLED')
  AND completed_at < now() - interval '30 days'
`

func (q *Queries) DeleteOldIngestionJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldIngestionJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldOutboxEvents = `-- name: DeleteOldOutboxEvents :execrows
DELETE FROM outbox_events
WHERE published_at < now() - interval '30 days'
   OR dead_lettered_at < now() - interval '90 days'
`

func (q *Queries) DeleteOldOutboxEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldOutboxEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldVerificationChallenges = `-- name: DeleteOldVerificationChallenges :execrows
DELETE FROM verification_challenges
WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteOldVerificationChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldVerificationChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hardDeleteCleanedDocuments = `-- name: HardDeleteCleanedDocuments :execrows
DELETE FROM documents document
USING artifact_cleanup_jobs cleanup
WHERE cleanup.document_id = document.id
  AND cleanup.state = 'SUCCEEDED'
  AND document.deleted_at < now() - interval '30 days'
`

func (q *Queries) HardDeleteCleanedDocuments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteCleanedDocuments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hardDeleteWithdrawnAccounts = `-- name: HardDeleteWithdrawnAccounts :execrows
DELETE FROM accounts account
WHERE account.deleted_at < now() - interval '7 days'
  AND NOT EXISTS (
    SELECT 1
    FROM documents document
    LEFT JOIN artifact_cleanup_jobs cleanup ON cleanup.document_id = document.id
    WHERE document.owner_id = account.id
      AND (cleanup.id IS NULL OR cleanup.state <> 'SUCCEEDED')
  )
`

func (q *Queries) HardDeleteWithdrawnAccounts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteWithdrawnAccounts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
