// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AccountPlan string

const (
	AccountPlanFREE AccountPlan = "FREE"
	AccountPlanPLUS AccountPlan = "PLUS"
)

func (e *AccountPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountPlan(s)
	case string:
		*e = AccountPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountPlan: %T", src)
	}
	return nil
}

type NullAccountPlan struct {
	AccountPlan AccountPlan `json:"account_plan"`
	Valid       bool        `json:"valid"` // Valid is true if AccountPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountPlan) Scan(value interface{}) error {
	if value == nil {
		ns.AccountPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountPlan), nil
}

type AccountRole string

const (
	AccountRoleUSER  AccountRole = "USER"
	AccountRoleADMIN AccountRole = "ADMIN"
)

func (e *AccountRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountRole(s)
	case string:
		*e = AccountRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountRole: %T", src)
	}
	return nil
}

type NullAccountRole struct {
	AccountRole AccountRole `json:"account_role"`
	Valid       bool        `json:"valid"` // Valid is true if AccountRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountRole) Scan(value interface{}) error {
	if value == nil {
		ns.AccountRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountRole), nil
}

type ChallengePurpose string

const (
	ChallengePurposeSIGNUP        ChallengePurpose = "SIGNUP"
	ChallengePurposePASSWORDRESET ChallengePurpose = "PASSWORD_RESET"
	ChallengePurposeWITHDRAW      ChallengePurpose = "WITHDRAW"
)

func (e *ChallengePurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengePurpose(s)
	case string:
		*e = ChallengePurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengePurpose: %T", src)
	}
	return nil
}

type NullChallengePurpose struct {
	ChallengePurpose ChallengePurpose `json:"challenge_purpose"`
	Valid            bool             `json:"valid"` // Valid is true if ChallengePurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengePurpose) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengePurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengePurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengePurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengePurpose), nil
}

type DocumentStatus string

const (
	DocumentStatusDRAFT            DocumentStatus = "DRAFT"
	DocumentStatusSCRAPEPENDING    DocumentStatus = "SCRAPE_PENDING"
	DocumentStatusSCRAPEPROCESSING DocumentStatus = "SCRAPE_PROCESSING"
	DocumentStatusSCRAPEREJECTED   DocumentStatus = "SCRAPE_REJECTED"
	DocumentStatusENRICHPENDING    DocumentStatus = "ENRICH_PENDING"
	DocumentStatusENRICHPROCESSING DocumentStatus = "ENRICH_PROCESSING"
	DocumentStatusENRICHREJECTED   DocumentStatus = "ENRICH_REJECTED"
	DocumentStatusCOMPLETED        DocumentStatus = "COMPLETED"
)

func (e *DocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentStatus(s)
	case string:
		*e = DocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentStatus: %T", src)
	}
	return nil
}

type NullDocumentStatus struct {
	DocumentStatus DocumentStatus `json:"document_status"`
	Valid          bool           `json:"valid"` // Valid is true if DocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentStatus), nil
}

type DocumentType string

const (
	DocumentTypeWEBPAGE DocumentType = "WEBPAGE"
	DocumentTypeMEMO    DocumentType = "MEMO"
	DocumentTypeIMAGE   DocumentType = "IMAGE"
	DocumentTypeFILE    DocumentType = "FILE"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType `json:"document_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type IngestionJobState string

const (
	IngestionJobStateQUEUED     IngestionJobState = "QUEUED"
	IngestionJobStatePROCESSING IngestionJobState = "PROCESSING"
	IngestionJobStateSUCCEEDED  IngestionJobState = "SUCCEEDED"
	IngestionJobStateFAILED     IngestionJobState = "FAILED"
	IngestionJobStateCANCELLED  IngestionJobState = "CANCELLED"
)

func (e *IngestionJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IngestionJobState(s)
	case string:
		*e = IngestionJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for IngestionJobState: %T", src)
	}
	return nil
}

type NullIngestionJobState struct {
	IngestionJobState IngestionJobState `json:"ingestion_job_state"`
	Valid             bool              `json:"valid"` // Valid is true if IngestionJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIngestionJobState) Scan(value interface{}) error {
	if value == nil {
		ns.IngestionJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IngestionJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIngestionJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IngestionJobState), nil
}

type IngestionJobType string

const (
	IngestionJobTypeSCRAPE    IngestionJobType = "SCRAPE"
	IngestionJobTypeENRICH    IngestionJobType = "ENRICH"
	IngestionJobTypeTHUMBNAIL IngestionJobType = "THUMBNAIL"
)

func (e *IngestionJobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IngestionJobType(s)
	case string:
		*e = IngestionJobType(s)
	default:
		return fmt.Errorf("unsupported scan type for IngestionJobType: %T", src)
	}
	return nil
}

type NullIngestionJobType struct {
	IngestionJobType IngestionJobType `json:"ingestion_job_type"`
	Valid            bool             `json:"valid"` // Valid is true if IngestionJobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIngestionJobType) Scan(value interface{}) error {
	if value == nil {
		ns.IngestionJobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IngestionJobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIngestionJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IngestionJobType), nil
}

type Account struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	Role         AccountRole        `json:"role"`
	Plan         AccountPlan        `json:"plan"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type ArtifactCleanupJob struct {
	ID           uuid.UUID          `json:"id"`
	DocumentID   uuid.UUID          `json:"document_id"`
	State        IngestionJobState  `json:"state"`
	AttemptCount int32              `json:"attempt_count"`
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
	LastError    pgtype.Text        `json:"last_error"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Chunk struct {
	ID              uuid.UUID          `json:"id"`
	DocumentID      uuid.UUID          `json:"document_id"`
	DocumentVersion int32              `json:"document_version"`
	ChunkIndex      int32              `json:"chunk_index"`
	SectionTitle    pgtype.Text        `json:"section_title"`
	Content         string             `json:"content"`
	PageNumber      pgtype.Int4        `json:"page_number"`
	EmbeddingModel  string             `json:"embedding_model"`
	Embedding       pgvector.Vector    `json:"embedding"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Collection struct {
	ID          uuid.UUID          `json:"id"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CollectionDocument struct {
	CollectionID uuid.UUID          `json:"collection_id"`
	DocumentID   uuid.UUID          `json:"document_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID             uuid.UUID          `json:"id"`
	OwnerID        uuid.UUID          `json:"owner_id"`
	Title          pgtype.Text        `json:"title"`
	Type           DocumentType       `json:"type"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	Content        pgtype.Text        `json:"content"`
	Summary        pgtype.Text        `json:"summary"`
	Status         DocumentStatus     `json:"status"`
	CurrentVersion int32              `json:"current_version"`
	ThumbnailUrl   pgtype.Text        `json:"thumbnail_url"`
	FileSize       int64              `json:"file_size"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	SearchVector   interface{}        `json:"search_vector"`
}

type DocumentTag struct {
	DocumentID uuid.UUID `json:"document_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

type DocumentVersion struct {
	ID                 uuid.UUID          `json:"id"`
	DocumentID         uuid.UUID          `json:"document_id"`
	Version            int32              `json:"version"`
	RawArtifactKey     pgtype.Text        `json:"raw_artifact_key"`
	ContentArtifactKey pgtype.Text        `json:"content_artifact_key"`
	ContentHash        pgtype.Text        `json:"content_hash"`
	Title              pgtype.Text        `json:"title"`
	Content            pgtype.Text        `json:"content"`
	Summary            pgtype.Text        `json:"summary"`
	ExtractionMethod   pgtype.Text        `json:"extraction_method"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	MediaType          pgtype.Text        `json:"media_type"`
}

type InboxEvent struct {
	EventID     string             `json:"event_id"`
	EventType   string             `json:"event_type"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LastError   pgtype.Text        `json:"last_error"`
}

type IngestionJob struct {
	ID               uuid.UUID          `json:"id"`
	DocumentID       uuid.UUID          `json:"document_id"`
	DocumentVersion  int32              `json:"document_version"`
	Type             IngestionJobType   `json:"type"`
	State            IngestionJobState  `json:"state"`
	AttemptCount     int32              `json:"attempt_count"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID             uuid.UUID          `json:"id"`
	EventType      string             `json:"event_type"`
	AggregateID    uuid.UUID          `json:"aggregate_id"`
	Payload        []byte             `json:"payload"`
	AttemptCount   int32              `json:"attempt_count"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	LockToken      pgtype.UUID        `json:"lock_token"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	DeadLetteredAt pgtype.Timestamptz `json:"dead_lettered_at"`
	LastError      pgtype.Text        `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	AccountID uuid.UUID          `json:"account_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID        uuid.UUID          `json:"id"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type VerificationChallenge struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Purpose      ChallengePurpose   `json:"purpose"`
	CodeHash     string             `json:"code_hash"`
	AttemptCount int32              `json:"attempt_count"`
	MaxAttempts  int32              `json:"max_attempts"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
