// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddDocumentToCollection(ctx context.Context, arg AddDocumentToCollectionParams) error
	AddTagToDocument(ctx context.Context, arg AddTagToDocumentParams) error
	BeginWebpageRefresh(ctx context.Context, arg BeginWebpageRefreshParams) (Document, error)
	ClaimArtifactCleanupJobs(ctx context.Context, batchSize int32) ([]ArtifactCleanupJob, error)
	ClaimEnrichmentJobs(ctx context.Context, limit int32) ([]IngestionJob, error)
	ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error)
	CompleteArtifactCleanupJob(ctx context.Context, id uuid.UUID) (int64, error)
	CompleteDocumentVersion(ctx context.Context, arg CompleteDocumentVersionParams) (int64, error)
	CompleteEnrichedVersion(ctx context.Context, arg CompleteEnrichedVersionParams) (int64, error)
	CompleteEnrichment(ctx context.Context, arg CompleteEnrichmentParams) (int64, error)
	CompleteInboxEvent(ctx context.Context, eventID string) error
	CompleteJob(ctx context.Context, id uuid.UUID) (int64, error)
	CompleteScrape(ctx context.Context, arg CompleteScrapeParams) (int64, error)
	ConsumeChallenge(ctx context.Context, id uuid.UUID) (int64, error)
	CountOwnedDocumentsByIDs(ctx context.Context, arg CountOwnedDocumentsByIDsParams) (int64, error)
	CountRecentChallenges(ctx context.Context, arg CountRecentChallengesParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateArtifactCleanupJob(ctx context.Context, arg CreateArtifactCleanupJobParams) error
	CreateChunk(ctx context.Context, arg CreateChunkParams) error
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error)
	CreateFileDocument(ctx context.Context, arg CreateFileDocumentParams) (Document, error)
	CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (IngestionJob, error)
	CreateMemo(ctx context.Context, arg CreateMemoParams) (Document, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateVerificationChallenge(ctx context.Context, arg CreateVerificationChallengeParams) (VerificationChallenge, error)
	CreateWebpage(ctx context.Context, arg CreateWebpageParams) (Document, error)
	DeadLetterOutboxEvent(ctx context.Context, arg DeadLetterOutboxEventParams) (int64, error)
	DeleteChallengesByEmail(ctx context.Context, email string) error
	DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (int64, error)
	DeleteDocumentCollections(ctx context.Context, documentID uuid.UUID) error
	DeleteDocumentTags(ctx context.Context, documentID uuid.UUID) error
	DeleteExpiredChallenges(ctx context.Context) error
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeleteOldInboxEvents(ctx context.Context) (int64, error)
	DeleteOldIngestionJobs(ctx context.Context) (int64, error)
	DeleteOldOutboxEvents(ctx context.Context) (int64, error)
	DeleteOldVerificationChallenges(ctx context.Context) (int64, error)
	DeleteUnusedTags(ctx context.Context, ownerID uuid.UUID) error
	EmailExists(ctx context.Context, email string) (bool, error)
	FailArtifactCleanupJob(ctx context.Context, arg FailArtifactCleanupJobParams) (int64, error)
	FailInboxEvent(ctx context.Context, arg FailInboxEventParams) error
	FailJob(ctx context.Context, arg FailJobParams) (int64, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetCollectionByName(ctx context.Context, arg GetCollectionByNameParams) (Collection, error)
	GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error)
	GetIngestionJob(ctx context.Context, id uuid.UUID) (IngestionJob, error)
	GetLatestOpenChallenge(ctx context.Context, arg GetLatestOpenChallengeParams) (VerificationChallenge, error)
	GetLatestVerifiedChallenge(ctx context.Context, arg GetLatestVerifiedChallengeParams) (VerificationChallenge, error)
	GetOwnedCurrentDocumentVersion(ctx context.Context, arg GetOwnedCurrentDocumentVersionParams) (DocumentVersion, error)
	GetOwnedDocument(ctx context.Context, arg GetOwnedDocumentParams) (Document, error)
	GetOwnedDocumentsByIDs(ctx context.Context, arg GetOwnedDocumentsByIDsParams) ([]Document, error)
	GetRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetStorageUsage(ctx context.Context, ownerID uuid.UUID) (int64, error)
	GetVerificationChallenge(ctx context.Context, arg GetVerificationChallengeParams) (VerificationChallenge, error)
	HardDeleteCleanedDocuments(ctx context.Context) (int64, error)
	HardDeleteWithdrawnAccounts(ctx context.Context) (int64, error)
	IncrementChallengeAttempt(ctx context.Context, id uuid.UUID) (VerificationChallenge, error)
	ListCollections(ctx context.Context, arg ListCollectionsParams) ([]ListCollectionsRow, error)
	ListDocumentArtifactKeys(ctx context.Context, documentID uuid.UUID) ([]ListDocumentArtifactKeysRow, error)
	ListDocumentTagNames(ctx context.Context, arg ListDocumentTagNamesParams) ([]ListDocumentTagNamesRow, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListDocumentsByCollection(ctx context.Context, arg ListDocumentsByCollectionParams) ([]Document, error)
	ListDocumentsByTag(ctx context.Context, arg ListDocumentsByTagParams) ([]Document, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error)
	LockAccountForStorage(ctx context.Context, id uuid.UUID) (Account, error)
	LockActiveAccount(ctx context.Context, id uuid.UUID) (Account, error)
	MarkChallengeVerified(ctx context.Context, id uuid.UUID) (int64, error)
	MarkDocumentEnrichProcessing(ctx context.Context, arg MarkDocumentEnrichProcessingParams) (int64, error)
	MarkDocumentProcessing(ctx context.Context, arg MarkDocumentProcessingParams) (int64, error)
	MarkJobProcessing(ctx context.Context, id uuid.UUID) (int64, error)
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error)
	RegisterInboxEvent(ctx context.Context, arg RegisterInboxEventParams) (string, error)
	RejectEnrichment(ctx context.Context, arg RejectEnrichmentParams) (int64, error)
	RejectScrape(ctx context.Context, arg RejectScrapeParams) (int64, error)
	RemoveDocumentFromCollection(ctx context.Context, arg RemoveDocumentFromCollectionParams) error
	RemoveOwnedDocumentFromCollection(ctx context.Context, arg RemoveOwnedDocumentFromCollectionParams) error
	RemoveTagFromDocument(ctx context.Context, arg RemoveTagFromDocumentParams) error
	ReplaceChunks(ctx context.Context, arg ReplaceChunksParams) error
	RequeueArtifactCleanupJob(ctx context.Context, documentID uuid.UUID) (int64, error)
	RescheduleOutboxEvent(ctx context.Context, arg RescheduleOutboxEventParams) error
	RevokeAllRefreshTokens(ctx context.Context, accountID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash []byte) error
	SaveExtractedContent(ctx context.Context, arg SaveExtractedContentParams) (int64, error)
	ScheduleAccountArtifactCleanup(ctx context.Context, ownerID uuid.UUID) error
	// pgvector 0.8 relaxed scans can be slightly out of order. PostgreSQL 18 needs
	// the explicit expression to perform a strict final ordering.
	SearchChunksVector(ctx context.Context, arg SearchChunksVectorParams) ([]SearchChunksVectorRow, error)
	SearchDocumentsLexical(ctx context.Context, arg SearchDocumentsLexicalParams) ([]SearchDocumentsLexicalRow, error)
	SearchDocumentsText(ctx context.Context, arg SearchDocumentsTextParams) ([]Document, error)
	SoftDeleteAccount(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteAccountDocuments(ctx context.Context, ownerID uuid.UUID) error
	SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (int64, error)
	UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateMemo(ctx context.Context, arg UpdateMemoParams) (Document, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
