// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retrieval.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const searchDocumentsLexical = `-- name: SearchDocumentsLexical :many
WITH query_input AS (
  SELECT websearch_to_tsquery('simple', $1::text) AS parsed
)
SELECT
  d.id AS document_id,
  (
    ts_rank_cd(d.search_vector, query_input.parsed, 32) * 2.0 +
    greatest(
      similarity(coalesce(d.title, ''), $1::text),
      similarity(coalesce(d.summary, ''), $1::text),
      similarity(coalesce(d.content, ''), $1::text)
    )
  )::float8 AS score
FROM documents d
CROSS JOIN query_input
WHERE d.owner_id = $2::uuid
  AND d.deleted_at IS NULL
  AND (
    d.search_vector @@ query_input.parsed
    OR coalesce(d.title, '') ILIKE '%' || $1::text || '%'
    OR coalesce(d.summary, '') ILIKE '%' || $1::text || '%'
    OR coalesce(d.content, '') ILIKE '%' || $1::text || '%'
  )
ORDER BY score DESC, d.updated_at DESC, d.id DESC
LIMIT $3::int
`

type SearchDocumentsLexicalParams struct {
	Query          string    `json:"query"`
	OwnerID        uuid.UUID `json:"owner_id"`
	CandidateLimit int32     `json:"candidate_limit"`
}

type SearchDocumentsLexicalRow struct {
	DocumentID uuid.UUID `json:"document_id"`
	Score      float64   `json:"score"`
}

func (q *Queries) SearchDocumentsLexical(ctx context.Context, arg SearchDocumentsLexicalParams) ([]SearchDocumentsLexicalRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentsLexical, arg.Query, arg.OwnerID, arg.CandidateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsLexicalRow{}
	for rows.Next() {
		var i SearchDocumentsLexicalRow
		if err := rows.Scan(&i.DocumentID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
