// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taxonomy.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDocumentToCollection = `-- name: AddDocumentToCollection :exec
INSERT INTO collection_documents (collection_id, document_id)
SELECT c.id, d.id
FROM collections c, documents d
WHERE c.id = $1
  AND d.id = $2
  AND c.owner_id = $3
  AND d.owner_id = $3
  AND d.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type AddDocumentToCollectionParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	DocumentID   uuid.UUID `json:"document_id"`
	OwnerID      uuid.UUID `json:"owner_id"`
}

func (q *Queries) AddDocumentToCollection(ctx context.Context, arg AddDocumentToCollectionParams) error {
	_, err := q.db.Exec(ctx, addDocumentToCollection, arg.CollectionID, arg.DocumentID, arg.OwnerID)
	return err
}

const addTagToDocument = `-- name: AddTagToDocument :exec
INSERT INTO document_tags (document_id, tag_id)
SELECT d.id, t.id
FROM documents d, tags t
WHERE d.id = $1
  AND t.id = $2
  AND d.owner_id = $3
  AND t.owner_id = $3
  AND d.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type AddTagToDocumentParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	TagID      uuid.UUID `json:"tag_id"`
	OwnerID    uuid.UUID `json:"owner_id"`
}

func (q *Queries) AddTagToDocument(ctx context.Context, arg AddTagToDocumentParams) error {
	_, err := q.db.Exec(ctx, addTagToDocument, arg.DocumentID, arg.TagID, arg.OwnerID)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (id, owner_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, description, created_at, updated_at
`

type CreateCollectionParams struct {
	ID          uuid.UUID   `json:"id"`
	OwnerID     uuid.UUID   `json:"owner_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, owner_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (owner_id, name)
DO UPDATE SET updated_at = now()
RETURNING id, owner_id, name, created_at, updated_at
`

type CreateTagParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.ID, arg.OwnerID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :execrows
DELETE FROM collections WHERE owner_id = $1 AND name = $2
`

type DeleteCollectionParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollection, arg.OwnerID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDocumentCollections = `-- name: DeleteDocumentCollections :exec
DELETE FROM collection_documents WHERE document_id = $1
`

func (q *Queries) DeleteDocumentCollections(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentCollections, documentID)
	return err
}

const deleteDocumentTags = `-- name: DeleteDocumentTags :exec
DELETE FROM document_tags WHERE document_id = $1
`

func (q *Queries) DeleteDocumentTags(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentTags, documentID)
	return err
}

const deleteUnusedTags = `-- name: DeleteUnusedTags :exec
DELETE FROM tags tag
WHERE tag.owner_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM document_tags relation WHERE relation.tag_id = tag.id
  )
`

func (q *Queries) DeleteUnusedTags(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnusedTags, ownerID)
	return err
}

const getCollectionByName = `-- name: GetCollectionByName :one
SELECT id, owner_id, name, description, created_at, updated_at FROM collections WHERE owner_id = $1 AND name = $2
`

type GetCollectionByNameParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) GetCollectionByName(ctx context.Context, arg GetCollectionByNameParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByName, arg.OwnerID, arg.Name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT c.id, c.name, c.description, COUNT(cd.document_id)::bigint AS document_count
FROM collections c
LEFT JOIN collection_documents cd ON cd.collection_id = c.id
WHERE c.owner_id = $1
GROUP BY c.id, c.name, c.description
ORDER BY c.updated_at DESC, c.id DESC
LIMIT $2 OFFSET $3
`

type ListCollectionsParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListCollectionsRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	DocumentCount int64       `json:"document_count"`
}

func (q *Queries) ListCollections(ctx context.Context, arg ListCollectionsParams) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsRow{}
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, COUNT(dt.document_id)::bigint AS document_count
FROM tags t
LEFT JOIN document_tags dt ON dt.tag_id = t.id
WHERE t.owner_id = $1::uuid
  AND ($2::text = '' OR t.name ILIKE '%' || $2 || '%')
GROUP BY t.id, t.name
ORDER BY document_count DESC, t.name
LIMIT $4::int OFFSET $3::int
`

type ListTagsParams struct {
	OwnerID    uuid.UUID `json:"owner_id"`
	Query      string    `json:"query"`
	PageOffset int32     `json:"page_offset"`
	PageSize   int32     `json:"page_size"`
}

type ListTagsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	DocumentCount int64     `json:"document_count"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags,
		arg.OwnerID,
		arg.Query,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.DocumentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentFromCollection = `-- name: RemoveDocumentFromCollection :exec
DELETE FROM collection_documents
WHERE collection_id = $1 AND document_id = $2
`

type RemoveDocumentFromCollectionParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	DocumentID   uuid.UUID `json:"document_id"`
}

func (q *Queries) RemoveDocumentFromCollection(ctx context.Context, arg RemoveDocumentFromCollectionParams) error {
	_, err := q.db.Exec(ctx, removeDocumentFromCollection, arg.CollectionID, arg.DocumentID)
	return err
}

const removeOwnedDocumentFromCollection = `-- name: RemoveOwnedDocumentFromCollection :exec
DELETE FROM collection_documents cd
USING collections c, documents d
WHERE cd.collection_id = c.id
  AND cd.document_id = d.id
  AND cd.collection_id = $1
  AND cd.document_id = $2
  AND c.owner_id = $3
  AND d.owner_id = $3
`

type RemoveOwnedDocumentFromCollectionParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	DocumentID   uuid.UUID `json:"document_id"`
	OwnerID      uuid.UUID `json:"owner_id"`
}

func (q *Queries) RemoveOwnedDocumentFromCollection(ctx context.Context, arg RemoveOwnedDocumentFromCollectionParams) error {
	_, err := q.db.Exec(ctx, removeOwnedDocumentFromCollection, arg.CollectionID, arg.DocumentID, arg.OwnerID)
	return err
}

const removeTagFromDocument = `-- name: RemoveTagFromDocument :exec
DELETE FROM document_tags dt
USING documents d, tags t
WHERE dt.document_id = d.id
  AND dt.tag_id = t.id
  AND dt.document_id = $1
  AND dt.tag_id = $2
  AND d.owner_id = $3
  AND t.owner_id = $3
`

type RemoveTagFromDocumentParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	TagID      uuid.UUID `json:"tag_id"`
	OwnerID    uuid.UUID `json:"owner_id"`
}

func (q *Queries) RemoveTagFromDocument(ctx context.Context, arg RemoveTagFromDocumentParams) error {
	_, err := q.db.Exec(ctx, removeTagFromDocument, arg.DocumentID, arg.TagID, arg.OwnerID)
	return err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $3, description = $4, updated_at = now()
WHERE owner_id = $1 AND name = $2
RETURNING id, owner_id, name, description, created_at, updated_at
`

type UpdateCollectionParams struct {
	OwnerID     uuid.UUID   `json:"owner_id"`
	Name        string      `json:"name"`
	Name_2      string      `json:"name_2"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.OwnerID,
		arg.Name,
		arg.Name_2,
		arg.Description,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
